//  StaffRosterAPIClient.h
//
//  Generated by the the JBoss AeroGear Xcode Project Template on 5/23/13.
//  See Project's web site for more details http://www.aerogear.org
//

#import "AeroGear.h"

@interface StaffRosterAPIClient : NSObject

@property(readonly, nonatomic) id<AGPipe> tasksPipe;

+ (StaffRosterAPIClient *)sharedInstance;
@end
